trigger:
  branches:
    include:
      - Master

pool:
  vmImage: 'windows-latest'


steps:
- checkout: self

- task: NuGetToolInstaller@1
  inputs:
    versionSpec: '>=5.0.0'
    checkLatest: true

- task: NuGetCommand@2
  displayName: 'NuGet Pack'
  inputs:
    command: 'pack'
    packagesToPack: (Build.SourcesDirectory)/001.nuspec
    versioningScheme: 'off'


- task: NuGetCommand@2
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: 'd8e6bb5f-2f36-4d8e-a95b-ecb54ece511f/b3ea81db-33ab-48e7-ad36-81bd9f943683'